### ISSUE TITLE
Multiple sources to one data source: label contains only first one

### ISSUE THREAD

**Issue by jakubklimek** [payola/LDVMi#43]
![image](https://cloud.githubusercontent.com/assets/718827/6690684/48b64c44-ccc2-11e4-88dc-bf3de5a9d814.png)
Here the datasource was 3 URLs

**Comment by jirihelmich** [comment]
I did it intentionally now, because I don't like the idea of 3 or more URLs
being displayed there. The label should be more clever like


"Combination of (...)" and in the visualization just first n chars visible,
or something like that.
út 17. 3. 2015 v 16:26 odesílatel Jakub Klímek <notifications@github.com>
napsal:

**Comment by jirihelmich** [comment]
Fixed, it contains all of them right now.
